### ISSUE TITLE
add option to configure cmake home

### ISSUE THREAD

**Issue by anb0s** [USESystemEngineeringBV/cmake-eclipse-helper#2]
Thanks for sharing the plugin :)

We have no cmake and other tools in PATH. The tools are located relative to the project container (multiple git repositories handled with own tool like repo or submodules). We need a possibility to configure path to the cmake executable or home, e.g. $CMAKE_HOME or better "${proejct_loc}/../tools/cmake_3.6.3". So variable support would be needed...

**Comment by anb0s** [comment]
So variable support would be needed... see #3

**Comment by DeHecht** [comment]
It should work by now, just like the other issue.

**Comment by anb0s** [comment]
Verified with "USE CMake Eclipse Support 1.0.22.201611161123"

Thank You!
