### ISSUE TITLE
set cmake build directory name

### ISSUE THREAD

**Issue by nicolalunghiemutex** [USESystemEngineeringBV/cmake-eclipse-helper#4]
Ho I can set the cmake build directory?
by default it sets to bin directory but I have another directory in my projects that have the same name

**Comment by DeHecht** [comment]
Good point. I can't promise to fix this today but I will try to make this configurable.

**Comment by DeHecht** [comment]
You should now be able to specify the output directory in the "Paths" settings.

**Comment by nicolalunghiemutex** [comment]
thanks!!

**Comment by nicolalunghiemutex** [comment]
I cannot find it in the project settings nor in the main settings! where it is? (I have eclipse neon)

**Comment by nicolalunghiemutex** [comment]
sorry my fault ! I find it and it works !! good work!! Thanks

**Comment by DeHecht** [comment]
sorry, I was just to late to post a link to the wiki :). Enjoy.
