### ISSUE TITLE
does not find toolchain

### ISSUE THREAD

**Issue by sancelot** [USESystemEngineeringBV/cmake-eclipse-helper#5]
I have got 3 toolchains in my eclipse neon project.
It does not propose it...

**Comment by DeHecht** [comment]
I can't completely follow you.
Have you set it up like described in the [wiki:HowToAddToolchain](https://github.com/USESystemEngineeringBV/cmake-eclipse-helper/wiki/HowToAddToolchain)?

**Comment by sancelot** [comment]
Ok. solved I missed the settings view !
